language: node_js
node_js:
  - '12'

#cache:
#  directories:
#    - $HOME/.composer/cache

before_install: true

install :
  - npm install

before_script: true

script:
  - "./node_modules/.bin/retire"
  - if [ "$TRAVIS_BRANCH" = "master" ]; then "./node_modules/.bin/twly"; fi
  - "./node_modules/.bin/jshint ./src/"


after_script: true

