language: node_js
php:
  - '12'

#cache:
#  directories:
#    - $HOME/.composer/cache

before_install: true

install :
  - npm install

before_script: true

script:
  - ./node_modules/.bin/jshint ./src

after_script: true

