language: node_js
node_js:
  - '12'

#cache:
#  directories:
#    - $HOME/.composer/cache

before_install: true

install :
  - npm install

before_script: true

script:
  - "./node_modules/.bin/retire"
  - "./node_modules/.bin/twly"
  - "./node_modules/.bin/jshint"

after_script: true

